export const QUOTES = [
  "Focus on being productive, not busy. — Tim Ferriss",
  "Action is the foundational key to all success. — Pablo Picasso",
  "What you do today can improve all your tomorrows. — Ralph Marston",
  "I choose progress over perfection.",
  "The way to get started is to quit talking and begin doing. — Walt Disney",
  "I act on what truly matters.",
  "Distraction is the enemy of progress; I choose focus.",
  "Do the hard things first. — Brian Tracy",
  "One day or day one — you decide.",
  "Less talk, more action.",
  "Motivation gets you going, but discipline keeps you growing. — John C. Maxwell",
  "Discipline is choosing between what you want now and what you want most. — Abraham Lincoln",
  "I keep promises I make to myself.",
  "Consistency compounds into greatness.",
  "I don’t wait for inspiration — I create it with discipline.",
  "Habits create results.",
  "Discipline is freedom. — Jocko Willink",
  "Success is nothing more than a few simple disciplines practiced daily. — Jim Rohn",
  "I show up, even on hard days.",
  "Small daily improvements lead to big results. — Robin Sharma",
  "Every challenge is an opportunity to grow.",
  "I am a lifelong learner.",
  "Doubt kills more dreams than failure ever will. — Suzy Kassem",
  "I learn something new every day.",
  "Mistakes are proof I am trying.",
  "Knowledge without action is wasted potential.",
  "I grow through what I go through.",
  "Education is the most powerful weapon you can use to change the world. — Nelson Mandela",
  "Growth begins at the end of your comfort zone.",
  "I improve 1% every day.",
  "I protect my energy and direct it wisely.",
  "Your mind is a garden; your thoughts are the seeds.",
  "I am in control of my time and my choices.",
  "I am calm, focused, and productive.",
  "Work smarter, not harder. — Allan F. Mogensen",
  "The mind is everything. What you think, you become. — Buddha",
  "I choose discipline over distraction.",
  "Energy flows where attention goes. — Tony Robbins",
  "Sometimes the most productive thing you can do is rest.",
  "I start my day with clarity and purpose.",
  "Don’t count the days, make the days count. — Muhammad Ali",
  "Done is better than perfect. — Sheryl Sandberg",
  "I am becoming the best version of myself.",
  "Success is the sum of small efforts repeated daily. — Robert Collier",
  "A year from now, you’ll wish you had started today. — Karen Lamb",
  "I am not afraid to fail; I am afraid not to try.",
  "Productivity is never an accident; it is the result of commitment and focus. — Paul J. Meyer",
  "I create results, not excuses.",
  "Opportunities don’t happen, you create them. — Chris Grosser",
  "I show up today with purpose and determination."
];
