name: Build & Release Extension

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Archive dist folder
        run: zip -r extension-dist.zip dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: extension-dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}